// <auto-generated />
using System;
using MBS.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBS.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250115154941_AddingShippingAddress")]
    partial class AddingShippingAddress
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MBS.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningPayable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningReceivable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Damage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Damages");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Division", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Division_BanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division_EngName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Divisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7625),
                            Division_BanName = "চট্টগ্রাম",
                            Division_EngName = "Chattagram",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7633)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7635),
                            Division_BanName = "রাজশাহী",
                            Division_EngName = "Rajshahi",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7635)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7636),
                            Division_BanName = "খুলনা",
                            Division_EngName = "Khulna",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7636)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7637),
                            Division_BanName = "বরিশাল",
                            Division_EngName = "Barishal",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7637)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7638),
                            Division_BanName = "সিলেট",
                            Division_EngName = "Sylhet",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7638)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7639),
                            Division_BanName = "ঢাকা",
                            Division_EngName = "Dhaka",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7639)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7640),
                            Division_BanName = "রংপুর",
                            Division_EngName = "Rangpur",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7640)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7641),
                            Division_BanName = "ময়মনসিংহ",
                            Division_EngName = "Mymensingh",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7641)
                        });
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubDistrictId")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("SubDistrictId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BarcodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PurchaseCost")
                        .HasColumnType("float");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float");

                    b.Property<int?>("SubUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArrival")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBestSaling")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLowStock")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductModels");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Due")
                        .HasColumnType("float");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Paid")
                        .HasColumnType("float");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.PurchasePayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionAccount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PurchasePayments");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<double?>("Due")
                        .HasColumnType("float");

                    b.Property<double?>("GrandTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Paid")
                        .HasColumnType("float");

                    b.Property<int?>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Profit")
                        .HasColumnType("float");

                    b.Property<double?>("PurchaseCost")
                        .HasColumnType("float");

                    b.Property<double?>("Receivable")
                        .HasColumnType("float");

                    b.Property<DateTime>("SalesDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.ShippingAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UnitId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OpeningPayable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningReceivable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RelatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedUnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedUnitId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.UserAddress.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7788),
                            DistrictName = "Chattagram",
                            DivisionId = 1,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7789)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7791),
                            DistrictName = "Rajshahi",
                            DivisionId = 2,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7791)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7792),
                            DistrictName = "Khulna",
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7792)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7793),
                            DistrictName = "Barishal",
                            DivisionId = 4,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7793)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7794),
                            DistrictName = "Sylhet",
                            DivisionId = 5,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7794)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7794),
                            DistrictName = "Dhaka",
                            DivisionId = 6,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7795)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7795),
                            DistrictName = "Rangpur",
                            DivisionId = 7,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7796)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7796),
                            DistrictName = "Mymensingh",
                            DivisionId = 8,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7796)
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7797),
                            DistrictName = "Noakhali",
                            DivisionId = 1,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7797)
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7798),
                            DistrictName = "Coxbazar",
                            DivisionId = 1,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7798)
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7799),
                            DistrictName = "Pabna",
                            DivisionId = 2,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7799)
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7799),
                            DistrictName = "Nator",
                            DivisionId = 2,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7800),
                            DistrictName = "Jashore",
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7801),
                            DistrictName = "Magura",
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7801)
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7802),
                            DistrictName = "MusnshiGanj",
                            DivisionId = 5,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7802)
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7803),
                            DistrictName = "ManikGanj",
                            DivisionId = 5,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7803)
                        });
                });

            modelBuilder.Entity("MBS.Models.EntityModel.UserAddress.SubDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubDistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DivisionId");

                    b.ToTable("SubDistricts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7817),
                            DistrictId = 1,
                            DivisionId = 1,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7818),
                            SubDistrictName = "Chattagram_sadar"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7819),
                            DistrictId = 2,
                            DivisionId = 2,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7819),
                            SubDistrictName = "Rajshahi_sadar"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7820),
                            DistrictId = 3,
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7820),
                            SubDistrictName = "Khulna_sadar"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7821),
                            DistrictId = 4,
                            DivisionId = 4,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7821),
                            SubDistrictName = "Barishal_sadar"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7822),
                            DistrictId = 6,
                            DivisionId = 6,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7822),
                            SubDistrictName = "Dhaka_sadar"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7823),
                            DistrictId = 13,
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7823),
                            SubDistrictName = "Monirampur"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7824),
                            DistrictId = 13,
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7824),
                            SubDistrictName = "Avainagar"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7824),
                            DistrictId = 14,
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7825),
                            SubDistrictName = "Shalikha"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7825),
                            DistrictId = 14,
                            DivisionId = 3,
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7826),
                            SubDistrictName = "Mohammadpur"
                        });
                });

            modelBuilder.Entity("MBS.Models.EntityModel.UserAddress.UserDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserDivisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7770),
                            DivisionName = "Chattagram",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7770)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7771),
                            DivisionName = "Rajshahi",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7772)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7772),
                            DivisionName = "Khulna",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7773)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7773),
                            DivisionName = "Barishal",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7773)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7774),
                            DivisionName = "Sylhet",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7774)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7775),
                            DivisionName = "Dhaka",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7775)
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7775),
                            DivisionName = "Rangpur",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7776)
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7776),
                            DivisionName = "Mymensingh",
                            ModifiedDate = new DateTime(2025, 1, 15, 21, 49, 40, 868, DateTimeKind.Local).AddTicks(7777)
                        });
                });

            modelBuilder.Entity("MBS.Models.PurchaseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("SubQuantity")
                        .HasColumnType("float");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseItems");
                });

            modelBuilder.Entity("MBS.Models.SalesItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.Property<double?>("SubTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SalesId");

                    b.ToTable("SalesItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Damage", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Location", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.UserAddress.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.UserAddress.UserDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.UserAddress.SubDistrict", "SubDistrict")
                        .WithMany()
                        .HasForeignKey("SubDistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Division");

                    b.Navigation("SubDistrict");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Product", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("MBS.Models.EntityModel.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Division");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.ProductModel", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Purchase", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Stock", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Product", "Product")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Unit", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Unit", "RelatedUnit")
                        .WithMany()
                        .HasForeignKey("RelatedUnitId");

                    b.Navigation("RelatedUnit");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.UserAddress.District", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.UserAddress.UserDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.UserAddress.SubDistrict", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.UserAddress.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.UserAddress.UserDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Division");
                });

            modelBuilder.Entity("MBS.Models.PurchaseItem", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.EntityModel.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MBS.Models.SalesItem", b =>
                {
                    b.HasOne("MBS.Models.EntityModel.Sales", "Sales")
                        .WithMany("SalesItems")
                        .HasForeignKey("SalesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MBS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MBS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MBS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MBS.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Product", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("MBS.Models.EntityModel.Sales", b =>
                {
                    b.Navigation("SalesItems");
                });
#pragma warning restore 612, 618
        }
    }
}
